# Generated by Django 5.1.7 on 2025-03-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
