# Generated by Django 5.1.7 on 2025-03-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
